export const getReceipts = 'banks'
export const getBank = 'banks/:addr'
export const createBank = 'banks'
export const getAllBank = 'banks'
export const sendCredit = 'banks/sendcredit'
export const getAllFinances = 'banks'
export const getAllFinanceAsks = 'banks'
